---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  :adapter: mysql
  :database: yak_dev
  :username: root
  :password: 
  :host: localhost
  :socket: /var/run/mysqld/mysqld.sock
  :encoding: utf8
 
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.db
  #   repo2:
  #     ...
 
test:
  <<:       *defaults
  :database: yak_test
 
  # repositories:
  #   repo1:
  #     database: sample_1_test.db
 
production:
  <<:       *defaults
  :database: yak
 
  # repositories:
  #   repo1:
  #     database: sample_production.db
 
rake:
  <<: *defaults
